import Head from 'next/head'
import Script from 'next/script'
import Image from 'next/image'
import { useEffect } from 'react'

export default function Home() {
  function clicked () {
    console.log('clicked...')
    if (document.getElementById("navbarResponsive").classList.contains("show")) {
      document.getElementById("navbarResponsive").classList.remove("show")
    }
    else {
        // document.getElementById("navbarResponsive").classList.add("show")
    }    
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond&display=swap" rel="stylesheet" />        
      </Head>
      <Script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
      />
      <Script src="/js/reveal.js" />
      {
        //<!-- Navigation-->
      }
      <nav className="reveal-custom navbar navbar-expand-lg navbar-dark fixed-top py-2" id="mainNav">
          <div className="container px-4 px-lg-5">
              <a className="navbar-brand" href="#page-top">St. Joseph the Worker</a>
              <button className="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span className="navbar-toggler-icon"></span></button>
              <div className="collapse navbar-collapse" id="navbarResponsive">
                  <ul className="navbar-nav ms-auto my-2 my-lg-0">
                      <li className="nav-item"><a onClick={clicked} className="nav-link" href="#past">Past</a></li>
                      <li className="nav-item"><a onClick={clicked} className="nav-link" href="#present">Present</a></li>
                      <li className="nav-item"><a onClick={clicked} className="nav-link" href="#future">Future</a></li>
                      <li className="nav-item"><a onClick={clicked} className="nav-link" href="#support">Support Us</a></li>
                  </ul>
              </div>
          </div>
      </nav>
      {
        //<!-- Masthead-->
      }
      <header className="masthead">
        <video id="bg-video" autoPlay muted loop>
          <source src="/img/bgvid.mp4" type="video/mp4" />
        </video>
        <div className="container px-4 px-lg-5 h-100">
            <div className="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                <div className="col-md-8 align-self-end">
                    <h1 className="text-gold font-weight-bold">Tradition & Beauty</h1>
                    <hr className="divider text-white" />
                </div>
                <div className="col-md-8 align-self-baseline">
                    <p className="text-white mb-5">Our Latin Mass community is growing and we need your help.</p>
                    <a className="btn btn-primary btn-xl bg-gold" href="#support">Support Us</a>
                </div>
            </div>
        </div>
      </header>      

      <section id="priority">
        <div className="container pb-5">
          <div className="row justify-content-center mt-5 py-5">
            <div className="col-sm-8 col-md-4 col-md-3 px-4 pb-5 mb-5 pb-md-0 mb-md-0"><p className="text-center" style={{fontSize:'4em'}}>1</p><p>Since 2003, St. Joseph the Worker Catholic Church has offered the Tridentine Latin Mass in the Diocese of Tyler.</p></div>
            <div className="col-sm-8 col-md-4 col-md-3 px-4 pb-5 mb-5 pb-md-0 mb-md-0"><p className="text-center" style={{fontSize:'4em'}}>2</p><p>Our growth has exceeded the capacity of our current cite. Parking and seating are no longer sufficient to accommodate all who would like to come.</p></div>
            <div className="col-sm-8 col-md-4 col-md-3 px-4 pb-5 mb-5 pb-md-0 mb-md-0"><p className="text-center" style={{fontSize:'4em'}}>3</p><p>Land has been generously donated giving us the opportunity to build something enduring for generations yet to come. Will you help us?</p></div>
          </div>
        </div>
      </section>



      <section id="past" style={{padding:'15px 0',backgroundImage:'linear-gradient(#f7f7f7, #fff)'}}>
        <div className="container">
          <div style={{margin:'120px 0'}} className="row justify-content-center">
            <div className="col-md-6">
              <h2>Past</h2>
              <p>The story of St. Joseph the Worker begins in 2003 in the Diocese of Tyler. Bishop Alvaro Corrada invited and welcomed the Priestly Fraternity of St. Peter to Tyler as a mission church of the Cathedral.</p>
              <p>From 2003 to 2006, the Extraordinary Form of the Mass was celebrated within the Diocesan Chancery Building in St. Paul's Chapel. In 2006, Bishop Corrada approved the acquisition of the current property that we now know and love and made St. Joseph the Worker a parish of the Diocese of Tyler.</p>
            </div>
            <div className="d-none d-md-block col-md-3 col-xl-2">
              <div style={{position:'relative',left:'0px'}}><Image src="/img/sjtw-current.png" width="768" height="526" alt="" /></div>
              <div style={{position:'relative',left:'30px',top:'-30px'}}><Image src="/img/sjtw-current.png" width="768" height="526" alt="" /></div>
              <div style={{position:'relative',left:'0px',top:'-60px'}}><Image src="/img/sjtw-current.png" width="768" height="526" alt="" /></div>
            </div>
            <div className="d-md-none col-md-3 col-xl-2 d-flex justify-content-center">
              <div style={{}}><Image src="/img/past/sjtw-current.png" width="768" height="526" alt="" /></div>
              <div style={{margin:'0 8px'}}><Image src="/img/past/sjtw-current.png" width="768" height="526" alt="" /></div>
              <div style={{}}><Image src="/img/past/sjtw-current.png" width="768" height="526" alt="" /></div>
            </div>
          </div>
        </div>
      </section>

      <section id="present" style={{background: "url('/img/present/jtw.jpg') center",backgroundSize:'cover'}}>
        <div className="container-fluid " style={{height:'800px'}}>
          <div className="row justify-content-center">
            <div className="col-md-6 mt-5 pt-5 text-white text-center">
              <h2>Present</h2>
              <p className="display-6" style={{marginTop:'250px'}}><span className="reveal" data-reveal="100">As the world darkens</span><span className="reveal" data-reveal="400">, people seek the light.</span></p>
            </div>
          </div>
        </div>
      </section>

      <section id="present2">
        <div className="container-fluid text-white pb-5" style={{backgroundColor:'#0d0e10'}}>
          <div className="row mb-5 py-5 justify-content-center">
            <div className=" col-md-4 col-sm-6">
              <h3>East Texas and St. Joseph the Worker have become the beacon of light and hope for a growing number of families.</h3>
              <p>With time, the community of St. Joseph the Worker has grown. In the past year, that growth has been exponential.</p>
            </div>
            <div className="offset-md-1 col-sm-3 d-none d-sm-block">
              <img className="" src="/img/present/mary-statue.png" style={{width:'100%',borderRadius:'15px'}} alt="" />
            </div>
          </div>
          <div className="row mb-5 pb-5 justify-content-center">
            <div className=" col-md-4 col-sm-6">
              <h3>Our growth has exceeded the capacity of our current site.</h3>
              <p>Parking and seating are no longer sufficient to accommodate all who would like to come. Our capacity, or lack thereof, has become our greatest limitation.</p>
              <p>Our beloved campus is also showing the scars of time. Rust stains decorate what was once new. The foundation and structural integrity of our parish hall is buckling under years of weather and wear. Aging pipes have leaked and broken, causing floods, water damage and mold.</p>
              <p>Despite these issues, our church is still beautiful. It is rich with memories and love from a devoted community for which it was the soil. We must continue to honor and respect it. It remains the House of God and the Gate of Heaven.</p>
            </div>
            <div className="offset-md-1 col-sm-3 d-none d-sm-block">
              <img className="" src="/img/present/tower.png" style={{width:'100%',borderRadius:'15px'}} alt="" />
            </div>
          </div>
          <div className="row mb-5 pb-5 justify-content-center">
            <div className=" col-md-4 col-sm-6">
              <h3>But now we have both the opportunity and responsibility to build anew.</h3>
              <p>To build a Church whose beauty gives due honor to our Priest, Prophet, and King; whose spaciousness is welcoming to friends and strangers alike. To build a new church and parish hall that will allow us to continue to plant the seeds of our community, cultivate it, and watch it thrive. To build up our beacon and shine brightly.</p>
            </div>
            <div className="offset-md-1 col-sm-3 d-none d-sm-block">
              <img className="" src="/img/present/psalm.png" style={{width:'100%',borderRadius:'15px'}} alt="" />
            </div>
          </div>
        </div>
      </section>
      <section id="present3">
        <div className="container-fluid py-5 py-md-0 px-0" style={{backgroundImage:'linear-gradient(#0d0e10, white)',position:'relative'}}>
          <Image
            src="/img/future/sjtw-wc.jpg"
            layout="responsive"
            width="1594"
            height="1163"
            style={{zIndex:'1'}}
            className="reveal"
            data-reveal="900" alt=""
          />          
          <div className="row astheworld text-center justify-content-center">
            <div className="text-white">
              <p id="future" className="display-6" style={{}}><span className="reveal" data-reveal="50">As the world darkens</span><span className="reveal" data-reveal="300">, our light must shine brighter. . .</span></p>
            </div>
          </div>
        </div>
      </section>     

      <section>
        <div className="container" style={{position:'relative',zIndex:3}}>
          <div className="row" style={{marginTop:'-180px'}}>
            <div className="offset-md-1 mb-5 mb-lg-0 col-md-10 col-lg-6 mt-5 mt-md-0" >
              <h2>Future</h2>
              <h3>Within our means, without compromising.</h3>
              <p>The aim of the building committee has been to design and develop a church that addresses our current needs while remaining affordable within the means of our community without compromising on traditional elements and beautiful design. Studio io, a Catholic architectural design firm with experience in traditional design, has been valuable in allowing us to fulfill all three goals.</p>
            </div>
            <div className="offset-md-1 col-md-3 d-none d-lg-block">
              <div className="reveal picframe" data-reveal="300" style={{top:'-30px',left:'-45px'}}><Image src="/img/future/sjtw-wc2.jpg" data-reveal="300" width="623" height="465" alt="" /></div>
              <div className="reveal picframe" data-reveal="300" style={{top:'-130px',left:'30px'}}><Image src="/img/future/sjtw-wc3.jpg" data-reveal="300" width="630" height="465" alt="" /></div>
              <div className="reveal picframe" data-reveal="300" style={{top:'-230px',left:'-90px'}}><Image src="/img/future/schematic.png" data-reveal="300" width="2544" height="1468" alt="" /></div>
            </div>

            <div className="offset-md-1 col-md-3 d-none d-lg-block">              
              <div className="reveal picframe" data-reveal="300" style={{top:'-120px',left:'30px'}}><Image src="/img/future/land.jpg" data-reveal="300" width="623" height="465" alt="" /></div>
              <div className="reveal picframe" data-reveal="300" style={{top:'-180px',left:'90px'}}><Image src="/img/future/map.png" data-reveal="300" width="768" height="628" alt="" /></div>
            </div>
            <div className="offset-md-1 mb-5 mb-lg-0 col-md-10 col-lg-6" >
              <h3>Land for the project has been secured.</h3>
              <p>Seven acres of land located off of highway 110 on the North side of Tyler has been generously donated to the cause. It is in a safer neighborhood surrounded by the homes of Catholic families.</p>
            </div>
          </div>
          <div className="row justify-content-center mb-5 pb-5">
            <div className="d-lg-none my-5">
              <Image 
                src="/img/future/schematic.png"
                width="2544"
                height="1468"
                alt=""
              />              
            </div>
            <div className="col-lg-4 mb-lg-0" >
              <h3>Divided into three principle phases.</h3>
              <p>Conceptually, the project has been divided into phases to provide smaller benchmarks for fundraising. This will allow for flexibility in the construction of the new campus with the ability to adapt its scope to match funds raised. <strong>The more we raise, the more we can build.</strong></p>
              <p>As it stands, the project is currently divided into three principle phases.</p>
            </div>
            <div className="d-none d-lg-block col-lg-6" style={{top:'-45px',position:'relative'}}>
              <Image 
                src="/img/future/schematic.png"
                width="2544"
                height="1468"
                alt=""
              />              
            </div>
          </div>

          <div className="row justify-content-center phase">
            <div className="col-md-8" >
              <Image 
                src="/img/future/phase1.jpg"
                width="1048"
                height="267"
                alt=""
              /> 
              <h3><strong>Phase 1: New church building with temporary sanctuary</strong> and no bell tower.</h3>
              <ul>
                <li>5,200 sq ft </li>
                <li>The initial phase of the church seats 300 people, counting 20" per person. By comparison, our current church seats ~100 people using the same calculation.</li>
                <li>The back wall of the sanctuary is temporary, allowing for continued use of the church during construction of the expansion, minimizing interruption.</li>
                <li>Two confessionals.</li>
                <li>Benches/pews with seating in the Narthex for nursing mothers</li>
                <li>Choir loft.</li>
              </ul>
            </div>
          </div>
          <div className="row justify-content-center phase">
            <div className="col-md-8" >
              <Image 
                src="/img/future/phase2.jpg"
                width="1048"
                height="267"
                alt=""
              /> 
              <h3><strong>Phase 2: Parish hall.</strong> Large main hall with a commercial kitchen and the capacity to accommodate parish-wide events, weddings, etc.</h3>
              <ul>
                <li>5,200 sq ft </li>
                <li>The initial phase of the church seats 300 people, counting 20" per person. By comparison, our current church seats ~100 people using the same calculation.</li>
                <li>The back wall of the sanctuary is temporary, allowing for continued use of the church during construction of the expansion, minimizing interruption.</li>
                <li>Two confessionals.</li>
                <li>Benches/pews with seating in the Narthex for nursing mothers</li>
                <li>Choir loft.</li>
              </ul>
            </div>
          </div>
          <div className="row justify-content-center phase">
            <div className="col-md-8" > 
              <Image 
                src="/img/future/phase3.jpg"
                width="1048"
                height="267"
                alt=""
              /> 
              <h3><strong>Phase 3: Expansion of the church building.</strong></h3>
              <ul>
                <li>The construction of this expansion can begin behind the temporary back wall of the sanctuary without disturbing the main church building itself, allowing for continued celebration of the Mass. Once the expansion is near completion, Mass celebrations can be moved temporarily to the parish hall while the two sections of the church are connected. This will minimize disruption while moving between phases.</li>
                <li>5,200 sq ft </li>
                <li>The initial phase of the church seats 300 people, counting 20" per person. By comparison, our current church seats ~100 people using the same calculation.</li>
                <li>The back wall of the sanctuary is temporary, allowing for continued use of the church during construction of the expansion, minimizing interruption.</li>
                <li>Two confessionals.</li>
                <li>Benches/pews with seating in the Narthex for nursing mothers</li>
                <li>Choir loft.</li>
              </ul>
            </div>
          </div>

          <div className="row justify-content-center phase mt-5">
            <div className="col-md-8" >

              <p>The current priority and most pressing need is to build a new church with more space, so Phase 1 is the primary goal.</p>
              <p><strong>Current preliminary estimated cost for Phase 1 is $1.721 Million.</strong> We are currently in the process of obtaining cost estimates for the parish hall and church expansion/bell tower.</p>
              <p>Bishop Strickland and FSSP leadership are supportive of exploring a plan to build our new church. The plan outlined in this book is pending approval from the Bishop and the Diocesan building committee.</p>
              <p>Once final approval has been granted, fundraising can begin. We would need to raise a minimum of 60% of total building costs to break ground, with the remaining 40% loaned to us from the Diocese to be paid back within 5 years. This 40% must be covered with pledges from donors.</p>

            </div>
          </div>
        </div>
      </section>

      <section id="studio" style={{backgroundImage:'linear-gradient(#f7f7f7, white)',position:'relative'}}>
        <div className="container section-spacing pt-5">
          <div className="row justify-content-center pt-5">
            <div className="col-md-8">
              <h2>Studio io</h2>
              <div className="d-flex justify-content-between pb-5">
                <div style={{background:"url('/img/studio/sio1.jpg') center",width:'120px',height:'120px',borderRadius:'50%',backgroundSize:'cover'}}></div>
                <div style={{background:"url('/img/studio/sio2.jpg') center",width:'120px',height:'120px',borderRadius:'50%',backgroundSize:'cover'}}></div>
                <div style={{background:"url('/img/studio/sio3.jpg') center",width:'120px',height:'120px',borderRadius:'50%',backgroundSize:'cover'}}></div>
                <div style={{background:"url('/img/studio/sio4.jpg') center",width:'120px',height:'120px',borderRadius:'50%',backgroundSize:'cover'}}></div>
              </div>
              <h4>We are a passionate team of faithful Catholic designers.</h4>
              <p>Founded in 2018, Studio io has assisted over 75 Catholic parishes, dioceses, campus ministries, schools, seminaries, religious communities, retreat centers, and other apostolates with design and consulting for beautifications, renovations, and new construction.</p>
              <h4>Our mission is beauty and order.</h4>
              <p>Instaurare Omnia (io) is a latin phrase meaning 'to renew all things'. Taken from the papal motto of Pope St. Pius X (Instaurare Omnia in Christo), who paved the way for a great deal of liturgical renewal prior to Vatican II, this phrase acknowledges the original beauty, order, dignity, and purpose of all creation to participate fully in the divine life and love of the Trinity through membership in the Mystical Body of Christ.</p>
              <h4>Our work is rooted in the Church's integrated vision for formation.</h4>
              <p>We incorporate liturgical & mystagogical catechesis into the church’s larger mission of evangelization. Our clients are devoted to providing a transforming encounter with Christ as the basis for renewal in the Church, as well as a commitment to forming disciples and re-establishing a wider culture of beauty as a privileged means for evangelization.</p>
              <p>WE FOSTER A SPECIAL DEVOTION TO THE HOLY FAMILY, ESPECIALLY VIA MARY, MOTHER OF THE CHURCH AND ST. JOSEPH THE WORKER</p>
            </div>
          </div>
        </div>
      </section>

      <section id="support" style={{backgroundImage:'linear-gradient(#faf3df, white)',position:'relative'}}>
        <div className="container section-spacing pt-5">
          <div className="row justify-content-center">
            <div className="col-md-8">
              <h2 className="py-5">Support Us</h2>
              <div style={{width:'100%', height:'500px', backgroundColor:'#ddd', color:'#777', fontSize:'2em', display:'flex', justifyContent:'center', alignItems:'center'}}>Donation Form</div>
            </div>
          </div>
        </div>
      </section>      

      <footer className="bg-gold section-spacing" style={{height:'200px'}}>

      </footer>

      <style jsx>{`
        .masthead {
          height: 100vh;
        }
        #bg-video {
          position: absolute;
          object-fit: cover;
          width: 100vw;
          height: 100vh;
          top: 0; left: 0;
          filter: brightness(0.7);
        }
        .masthead .container {
          
          position: relative;
        }
        section h2, h1 { 
          font-size: 6em;
          font-family: 'Cormorant Garamond'
        }
        h1 { font-size: 4em; }
        nav.reveal-custom {
          background: rgba(255,255,255,0);
          transition: all 0.5s ease;
        }
        nav.reveal-custom.active {
          background: rgba(200,165,69,1);
        }
        .section-spacing {
          margin-top: 120px;
        }
        .picframe {
          position:relative;
          border:1px solid #ccc;
          padding:15px;
          background-color:white;
          border-radius:15px;
        }
        .picframe img {
          border-radius: 15px;
        }
        .phase {
          margin: 90px 0;
        }
        .phase ul {
          margin: 30px 0;
        }
        .phase ul li {
          padding: 5px 0;
        }
        .astheworld {
          position: absolute;
          top:0;left:0;right:0;
          padding: 0px 0 400px 0;
          margin: 100px 0;
          zIndex: 0;
        }
        @media (min-width: 992px) { 
          .astheworld { padding: 200px 0 400px 0; }
          section h2, h1 { 
            font-size: 8em;
            font-family: 'Cormorant Garamond'
          }
          h1 { font-size: 6em; }
        }
      `}
      </style>
    </div>
  )
}
