import Head from 'next/head'
import Script from 'next/script'
// import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond&display=swap" rel="stylesheet" />        
      </Head>
      <Script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
      />
      {
        //<!-- Navigation-->
      }
      <nav className="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
          <div className="container px-4 px-lg-5">
              <a className="navbar-brand" href="#page-top">St. Joseph the Worker</a>
              <button className="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span className="navbar-toggler-icon"></span></button>
              <div className="collapse navbar-collapse" id="navbarResponsive">
                  <ul className="navbar-nav ms-auto my-2 my-lg-0">
                      <li className="nav-item"><a className="nav-link" href="#past">Past</a></li>
                      <li className="nav-item"><a className="nav-link" href="#present">Present</a></li>
                      <li className="nav-item"><a className="nav-link" href="#future">Future</a></li>
                      <li className="nav-item"><a className="nav-link" href="#support">Support Us</a></li>
                  </ul>
              </div>
          </div>
      </nav>
      {
        //<!-- Masthead-->
      }
      <header className="masthead">
          <div className="container px-4 px-lg-5 h-100">
              <div className="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                  <div className="col-lg-8 align-self-end">
                      <h1 className="text-gold font-weight-bold">Tradition & Beauty</h1>
                      <hr className="divider" />
                  </div>
                  <div className="col-lg-8 align-self-baseline">
                      <p className="text-white-75 mb-5">Our Latin Mass community is growing and we need your help.</p>
                      <a className="btn btn-light btn-xl" href="#about">Find Out More</a>
                  </div>
              </div>
          </div>
      </header>      

      <section id="priority">
        <div className="container">
          <div className="row gx-5 justify-content-center mt-5 py-5">
            <div className="col-3"><p>Since 2003, St. Joseph the Worker Catholic Church has offered the Tridentine Latin Mass in the Diocese of Tyler.</p></div>
            <div className="col-3"><p>Our growth has exceeded the capacity of our current cite. Parking and seating are no longer sufficient to accommodate all who would like to come.</p></div>
            <div className="col-3"><p>Land has been generously donated. Now we must build. Will you help us?</p></div>
          </div>
        </div>
      </section>



      <section id="past">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-8">
              <h2>Past</h2>
              <p>The story of St. Joseph the Worker begins in 2003 in the Diocese of Tyler. In an effort to take care of the spiritual needs of his Catholic community, Bishop Alvaro Corrada invited and welcomed the Priestly Fraternity of St. Peter to Tyler as a mission church of the Cathedral. The Fraternity offered the faithful celebration of the traditional Mass and Sacraments in the Extraordinary Form of the Roman Rite.</p>
              <p>From 2003 to 2006, the Extraordinary Form of the Mass was celebrated within the Diocesan Chancery Building in St. Paul's Chapel. In 2006, Bishop Corrada approved the acquisition of the current property that we now know and love. The dedication ceremony was on April 8th, 2006. In 2011, Bishop Corrada made St. Joseph the Worker a parish of the Diocese of Tyler.</p>
              <p>Father Carlos Casavantes was the first priest to come. He served from 2003 until 2007, when he was replaced by Father Scott Allen, who served until 2015. From 2015 to 2017, Father Joseph Terra and Father Phillip Wolfe served together. Father Joseph Valentine joined in 2017.</p>
            </div>
          </div>
        </div>
      </section>

      <section id="present">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-8">
              <h2>Present</h2>
              <p>As the world darkens, people seek the light. They seek the opportunity to practice their faith freely; to celebrate the full Truth and Beauty of the Catholic faith. They seek strong leadership who holds fast to the teachings of our Catholic Church. They seek a community whose eyes are directed at God, away from the secularization and commercialization of the world around them.</p>
              <p>East Texas and St. Joseph the Worker have become that beacon of light and hope for many families. With time, the community of St. Joseph the Worker has grown. In the past year, that growth has been exponential.</p>
              <p>Our growth has exceeded the capacity of our current site. Parking and seating are no longer sufficient to accommodate all who would like to come. Our capacity, or lack thereof, has become our greatest limitation.</p>
              <p>Our beloved campus is also showing the scars of time. Rust stains decorate what was once new. The foundation and structural integrity of our parish hall is buckling under years of weather and wear. Aging pipes have leaked and broken, causing floods, water damage and mold.</p>
              <p>Despite these issues, our church is still beautiful. It is rich with memories and love from a devoted community for which it was the soil. We must continue to honor and respect it. It remains the House of God and the Gate of Heaven.</p>
              <p>But now we have both the opportunity and responsibility to build anew. To build a Church whose beauty gives due honor to our Priest, Prophet, and King; whose spaciousness is welcoming to friends and strangers alike. To build a new church and parish hall that will allow us to continue to plant the seeds of our community, cultivate it, and watch it thrive. To build up our beacon and shine brightly. As the world darkens, our light must shine brighter. . .</p>
            </div>
          </div>
        </div>
      </section>

      <section id="future">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-8">
              <h2>Future</h2>
              <p>From the beginning, the aim of the building committee has been to design and develop a church that addresses our current needs while remaining affordable within the means of our community without compromising on traditional elements and beautiful design. Studio io, a Catholic architectural design firm with experience in traditional design, has been valuable in allowing us to fulfill all three goals.</p>
              <p>The land for the project has been secured. Seven acres of land located off of highway 110 on the North side of Tyler has been generously donated to the cause. It is in a safer neighborhood surrounded by the homes of Catholic families.</p>
              <p>Conceptually, the project has been divided into phases to provide smaller benchmarks for fundraising. This will allow for flexibility in the construction of the new campus with the ability to adapt its scope to match funds raised. <strong>The more we raise, the more we can build.</strong></p>
              <p>As it stands, the project is currently divided into three principle phases.</p>
              <ol>
                <li><strong>Phase 1: New church building with temporary sanctuary</strong> and no bell tower.</li>
                <li><strong>Phase 2: Parish hall.</strong> Large main hall with a commercial kitchen and the capacity to accommodate parish-wide events, weddings, etc.</li>
                <li><strong>Phase 3: Expansion of the church building.</strong> The construction of this expansion can begin behind the temporary back wall of the sanctuary without disturbing the main church building itself, allowing for continued celebration of the Mass. Once the expansion is near completion, Mass celebrations can be moved temporarily to the parish hall while the two sections of the church are connected. This will minimize disruption while moving between phases.</li>
              </ol>
              <p>The current priority and most pressing need is to build a new church with more space, so Phase 1 is the primary goal.</p>
              <p><strong>Current preliminary estimated cost for Phase 1 is $1.721 Million.</strong> We are currently in the process of obtaining cost estimates for the parish hall and church expansion/bell tower.</p>
              <p>Bishop Strickland and FSSP leadership are supportive of exploring a plan to build our new church. The plan outlined in this book is pending approval from the Bishop and the Diocesan building committee.</p>
              <p>Once final approval has been granted, fundraising can begin. We would need to raise a minimum of 60% of total building costs to break ground, with the remaining 40% loaned to us from the Diocese to be paid back within 5 years. This 40% must be covered with pledges from donors.</p>

            </div>
          </div>
        </div>
      </section>

      <section id="past">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-8">
              <h2>Studio io</h2>

              <p>WE ARE A PASSIONATE TEAM OF FAITHFUL CATHOLIC DESIGNERS.</p>
              <p>Founded in 2018, Studio io has assisted over 75 Catholic parishes, dioceses, campus ministries, schools, seminaries, religious communities, retreat centers, and other apostolates with design and consulting for beautifications, renovations, and new construction.</p>
              <p>OUR MISSION IS BEAUTY AND ORDER.</p>
              <p>Instaurare Omnia (io) is a latin phrase meaning 'to renew all things'. Taken from the papal motto of Pope St. Pius X (Instaurare Omnia in Christo), who paved the way for a great deal of liturgical renewal prior to Vatican II, this phrase acknowledges the original beauty, order, dignity, and purpose of all creation to participate fully in the divine life and love of the Trinity through membership in the Mystical Body of Christ.</p>
              <p>OUR WORK IS ROOTED IN THE CHURCH’S INTEGRATED VISION FOR FORMATION.</p>
              <p>We incorporate liturgical & mystagogical catechesis into the church’s larger mission of evangelization. Our clients are devoted to providing a transforming encounter with Christ as the basis for renewal in the Church, as well as a commitment to forming disciples and re-establishing a wider culture of beauty as a privileged means for evangelization.</p>
              <p>WE FOSTER A SPECIAL DEVOTION TO THE HOLY FAMILY, ESPECIALLY VIA MARY, MOTHER OF THE CHURCH AND ST. JOSEPH THE WORKER</p>


            </div>
          </div>
        </div>
      </section>

      <section id="support">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-8">
              <h2>Support Us</h2>
              <div style={{width:'100%', height:'500px', backgroundColor:'#ccc', color:'#777', fontSize:'2em', display:'flex', justifyContent:'center', alignItems:'center'}}>Donation Form</div>
            </div>
          </div>
        </div>
      </section>      

      <footer className="bg-gold mt-5" style={{height:'200px'}}>

      </footer>

      <style jsx>{`
        .masthead {
          background: url('/img/sjtw-wc.jpg') no-repeat center;
          background-size: cover;
          height: 100vh;
        }
        section h2, h1 { 
          font-size: 4em;
          margin-top: 45px;
          font-family: 'Cormorant Garamond'
        }
      `}
      </style>
    </div>
  )
}
